stages:
  - build_esp32

variables:
  BATCH_BUILD: "1"
  V: "0"
  MAKEFLAGS: "-j5 --no-keep-going"
  IDF_PATH: "$CI_PROJECT_DIR/esp-idf"
  IDF_CI_BUILD: "1"

build_esp32_demo:
  stage: build_esp32
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  tags:
    - build
  script:
    # add gitlab ssh key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY > ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git --version
    - git submodule update --init --recursive
    - git clone -b v4.1 --recursive --depth 1 $GITLAB_SSH_SERVER/idf/esp-idf.git
    - export PATH="$IDF_PATH/tools:$PATH"
    - cd esp-idf
    - ./install.sh
    - . export.sh
    - cd ..
    - cd examples/azure_iot_pnp_sample/pnp_temperature_controller
    - make defconfig && make -j5
    - make clean && rm sdkconfig && rm -r build
    - echo "CONFIG_COMPILER_OPTIMIZATION_LEVEL_RELEASE=y" >> sdkconfig.defaults
    - make defconfig && make -j5
    - make clean && rm sdkconfig && rm -r build
    - idf.py build
